name: Docker Image CI Prod

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Global Variables
      run: echo "version=1.3.1-slim" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sucwangsr/janus-webrtc-gateway-docker:$version
    - name: push hub
      run: docker login -u ${{secrets.HUB_USER}} -p ${{secrets.HUB_PWD}} && docker push sucwangsr/janus-webrtc-gateway-docker:$version && docker logout
